#!/usr/bin/env bash

appname=$(basename $0)

# initialize configuration folder when it is not existing
configFolder="${XDG_CONFIG_HOME:-$HOME/.config}/$appname"
if [[ ! -d "$configFolder" ]]; then
	mkdir -p "$configFolder"
fi

function usage() {
    local return=$1
    if [[ -z $return ]]; then
        return=0
    fi
    echo "$appname - simply sync your folders"
    echo ""
    echo "Usage: $appname [options] profile"
    echo "       $appname --up --run test"
    echo "       $appname -u -r test"
    echo "       $appname --down test"
    echo "       $appname -d test"
    echo "       $appname -l"
    echo "       $appname --help"
    echo ""
    echo "Options"
    echo " -u, --up      sync up"
    echo " -d, --down    sync down"
    echo " -x, --remove  also run delete"
    echo " -r, --run     actually sync (if not given dry run is done)"
    echo " -l, --list    show the profile configurations"
    echo " -h, --help    show this help"

    exit $return
}

function  listProfiles() {
    ls $configFolder/*.cfg | sed 's/.*\/\([a-z0-9_-]\+\)\.cfg/\1/g'

    exit 0
}

# config options
LFOLDER=""
RFOLDER=""
SSH=0

PROFILE=''

# cli options
DIRECTION='up'
DRYRUN=1
DELETE=0

# getopts
while true; do
    case "$1" in
        -u | --up ) DIRECTION='up'; shift ;;
        -d | --down ) DIRECTION='down'; shift ;;
        -x | --remove ) DELETE=1; shift ;;
        -r | --run ) DRYRUN=0; shift ;;
        -l | --list ) listProfiles; shift ;;
        -h | --help ) usage; shift ;;
        * ) if [[ "" == "$PROFILE" ]]; then PROFILE="$1"; fi; shift ;;
    esac
    if [[ 0 -eq $# ]]; then
        break;
    fi
done

if [[ -z $PROFILE ]]; then
    echo "error: you should pass a profile";
    echo ""
    usage 250
fi

# if exists load config file, see documents-sync.cfg.example
if [[ -e "$configFolder/$PROFILE.cfg" ]]; then
	source "$configFolder/$PROFILE.cfg"
else
	echo "error: the profile has no config file"
    echo ""
	usage 250
fi

# exclude
if [[ ! -e "$configFolder/$PROFILE.exclude" ]]; then
	touch "$configFolder/$PROFILE.exclude"
fi

# checks for empty config vars
[[ -z "$LFOLDER" ]] && echo "Local folder (LFOLDER) must be configured" && exit 255
[[ -z "$RFOLDER" ]] && echo "Remote folder (RFOLDER) must be configured" && exit 255
if [[ $SSH -ne 1 ]]; then
	SSH=0
fi

# check the folders
if [[ "${LFOLDER: -1}" != "/" ]]; then
    LFOLDER="$LFOLDER/"
fi

if [[ "${RFOLDER: -1}" != "/" ]]; then
    RFOLDER="$RFOLDER/"
fi

case "$DIRECTION" in
'up')
	folders="$LFOLDER $RFOLDER"
	;;
'down')
	folders="$RFOLDER $LFOLDER"
	;;
esac

if [[ $DRYRUN -ne 0 ]]; then
	dry=' --dry-run'
else
	dry=''
fi

if [[ $DELETE -eq 1 ]]; then
    remove=' --delete-after'
else
    remove=''
fi

if [[ $SSH -eq 1 ]]; then
	ssh=' -e ssh'
else
	ssh=''
fi

banner="$appname '$PROFILE' $DIRECTION"
if [[ $DRYRUN -ne 0 ]]; then
    banner="$banner - !DRY RUN!"
fi
echo "$banner"
echo "$(echo $banner | sed 's/./-/g')"

rsync \
	$dry \
	--archive \
	--modify-window=10 \
	--update \
	$remove \
	--omit-dir-times \
	--no-owner \
	--no-group \
	--itemize-changes \
	$ssh \
	--exclude-from "$configFolder/$PROFILE.exclude" \
	$folders
